### ISSUE TITLE
GitHub Stats

### ISSUE THREAD

**Issue by Zarinha** [thatblindgeye/thatblindgeye#1]
Hi @thatblindgeye I'm still aspiring to web development and I still don't have much knowledge in the area. But I found your presentation on GitHub Readme interesting. Then I noticed that your charts have outdated data.
By compare:
![Screenshot from 2022-04-07 20-34-21](https://user-images.githubusercontent.com/100753264/162274019-5bec01c4-e5f6-4980-bc42-ec9eebb745c9.png)
and:
<https://github-readme-stats.vercel.app/api?username=thatblindgeye&amp;hide=stars&amp;show_icons=true&amp;theme=midnight-purple&amp;include_all_commits=true>

**Comment by thatblindgeye** [comment]
Hm that's odd! This is what I see when viewing my own profile:

![thatblindgeye GitHub stats](https://user-images.githubusercontent.com/70952936/162275563-0672bffc-fdf1-49df-858c-00fe2c198269.png)

Not sure if it's just a weird bug you're seeing or maybe I'm not seeing it because it's my own profile.

**Comment by Zarinha** [comment]
Now it is normal for me as well. Probably a temporary bug. xD

**Comment by thatblindgeye** [comment]
Perhaps an issue with fetching the data or something like that. Thanks for wanting to mention it to me! Gonna close this since ~~GitHub~~ you fixed it 😆
